pipeline:
  name: pipinyaml
  identifier: pipinyaml
  projectIdentifier: Default_Project_1669294861098
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gh
        repoName: test
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build234
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: pwd2
                  identifier: pwd
                  spec:
                    shell: Sh
                    command: ls
    - stage:
        name: run pip
        identifier: run_pip
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: Build_project1_1669294954139
          project: Default_Project_1669294861098
          inputs:
            identifier: Build_project1_1669294954139
            properties:
              ci:
                codebase:
                  build: <+input>
